### PR TITLE
convert to Unity Package

### PR DESCRIPTION
**Pull request by radiatoryang**
this PR reorganizes this repo into a Unity package https://docs.unity3d.com/Manual/cus-layout.html ... for discussion see #15 

- added package.json manifest, added .asmdef
- moved all files into /Editor/ and /Runtime/ folders, per Unity Package convention
- tried to maintain existing folder structure + .meta files, all GUIDs should be the same

seems to work ok as of Unity 2021.2... here's a random BSP I had

image

### CODE REVIEW

**Comment by wfowler1** [comment]
Looks good, I'll have to try this out a bit more.

**Comment by wfowler1** [comment]
Oh, uh, if I pull it using the Package Manager, it's missing LibBSP. What was the plan for that?

**Comment by radiatoryang** [comment]
Oh uhhh I've been assuming this whole time that UPM did submodule operations... and I guess I was wrong?

The plan would be to run a GitHub workflow that automatically compiles LibBSP and brings it into this repo, like https://github.com/YarnSpinnerTool/YarnSpinner-Unity/blob/main/.github/workflows/update_dlls.yml

Maybe revert for now, and I can try to figure it out

**Comment by wfowler1** [comment]
It does look like the submodule got pulled along with the package, all the files are there in the Library\PackageCache\com.wfowler1.unity3d-bsp-importer@864ea09b7f\Runtime\External\LibBSP folder. It looks like it just can't find the namespaces.

**Comment by radiatoryang** [comment]
Yeah bizarre, Unity is just ignoring the submodule files even though it pulls them. I'm now seeing import error messages like `Asset Packages/com.wfowler1.unity3d-bsp-importer/Runtime/External/LibBSP/LibBSP/Source/Attributes/CountAttribute.cs has no meta file, but it's in an immutable folder. The asset will be ignored.`

Should I work on a PR for an automated LibBSP compiling GitHub workflow thing? Sorry again.

**Comment by radiatoryang** [comment]
Oh, wait, actually that makes perfect sense. Of course packages are immutable, and of course it wouldn't just generate random meta files and overwrite a package. 

Again I think you have two options: revert this and don't use UPM, or do a Github automated workflow thing to compile and pull LibBSP.dll into the repo.

**Comment by wfowler1** [comment]
I'm fine with the GitHub automated workflow thing, that sounds neat. In the meantime, this package is no less functional than it was before when you pull it into a project normally. I don't think we need to revert it just now.

**Pull request merged**
